import { useState } from "react";
import { Download, FileText, FileCode, Loader2, CheckCircle } from "lucide-react";
import { cn } from "@/lib/utils";
import type { SummarySection } from "@/components/SummaryPanel";
import type { VerificationStats } from "@/components/TransparencyPanel";
import type { ExecutiveAlert } from "@/components/ExecutiveAlerts";

interface ReportExporterProps {
  fileName: string | null;
  summaries: SummarySection[];
  verificationStats: VerificationStats | null;
  executiveAlerts: ExecutiveAlert[];
}

type ExportFormat = "markdown" | "json";

function generateMarkdownReport(
  fileName: string | null,
  summaries: SummarySection[],
  stats: VerificationStats | null,
  alerts: ExecutiveAlert[]
): string {
  const lines: string[] = [];
  const date = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  lines.push(`# 📄 Document Intelligence Report`);
  lines.push(`**Document:** ${fileName || "Unknown"}`);
  lines.push(`**Generated:** ${date}`);
  lines.push(`**Platform:** GhostCut — Intelligent Document Platform`);
  lines.push("");

  // Verification stats
  if (stats) {
    lines.push(`## 📊 Verification Summary`);
    lines.push(`| Metric | Value |`);
    lines.push(`|--------|-------|`);
    lines.push(`| Confidence Score | ${stats.confidenceScore}% |`);
    lines.push(`| Verified Facts | ${stats.verifiedFacts}/${stats.totalFacts} |`);
    lines.push(`| Hallucination Risk | ${stats.hallucinationRisk.toUpperCase()} |`);
    if (stats.compressionRatio !== undefined) {
      lines.push(`| Compression Ratio | ${stats.compressionRatio}% |`);
    }
    if (stats.redundancyScore !== undefined) {
      lines.push(`| Deduplication Score | ${stats.redundancyScore}% |`);
    }
    if (stats.abstractionLevel) {
      lines.push(`| Abstraction Level | ${stats.abstractionLevel.charAt(0).toUpperCase() + stats.abstractionLevel.slice(1)} |`);
    }
    lines.push("");
  }

  // Executive Alerts
  if (alerts.length > 0) {
    lines.push(`## 🚨 Executive Alerts`);
    alerts.forEach((alert) => {
      const icon = alert.severity === "high" ? "🔴" : alert.severity === "medium" ? "🟡" : "🔵";
      lines.push(`### ${icon} ${alert.title}`);
      lines.push(`- **Category:** ${alert.category}`);
      lines.push(`- **Severity:** ${alert.severity.toUpperCase()}`);
      lines.push(`- **Description:** ${alert.description}`);
      lines.push(`- **Evidence:** ${alert.evidence}`);
      if (alert.recommendation) {
        lines.push(`- **Recommendation:** ${alert.recommendation}`);
      }
      lines.push("");
    });
  }

  // Summaries
  if (summaries.length > 0) {
    lines.push(`## 📝 Document Summary`);
    summaries.forEach((section) => {
      lines.push(`### ${section.title}`);
      const statusIcon = section.verificationStatus === "verified" ? "✅" : section.verificationStatus === "conflict" ? "❌" : "⚠️";
      lines.push(`${statusIcon} *${section.verificationStatus || "unverified"}*`);
      lines.push("");
      lines.push(section.summary);
      lines.push("");

      if (section.evidence) {
        lines.push(`> **Source Evidence:** ${section.evidence}`);
        lines.push("");
      }

      if (section.children) {
        section.children.forEach((child) => {
          lines.push(`#### ${child.title}`);
          lines.push(child.summary);
          lines.push("");
          if (child.evidence) {
            lines.push(`> ${child.evidence}`);
            lines.push("");
          }
        });
      }
    });
  }

  lines.push("---");
  lines.push(`*Report generated by GhostCut — Intelligent Document Platform*`);

  return lines.join("\n");
}

export function ReportExporter({ fileName, summaries, verificationStats, executiveAlerts }: ReportExporterProps) {
  const [exporting, setExporting] = useState<ExportFormat | null>(null);
  const [exported, setExported] = useState<ExportFormat | null>(null);

  const handleExport = (format: ExportFormat) => {
    setExporting(format);

    setTimeout(() => {
      let content: string;
      let mimeType: string;
      let extension: string;

      if (format === "markdown") {
        content = generateMarkdownReport(fileName, summaries, verificationStats, executiveAlerts);
        mimeType = "text/markdown";
        extension = "md";
      } else {
        content = JSON.stringify(
          { fileName, summaries, verificationStats, executiveAlerts, exportedAt: new Date().toISOString() },
          null,
          2
        );
        mimeType = "application/json";
        extension = "json";
      }

      const blob = new Blob([content], { type: mimeType });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${fileName || "document"}-report.${extension}`;
      a.click();
      URL.revokeObjectURL(url);

      setExporting(null);
      setExported(format);
      setTimeout(() => setExported(null), 2000);
    }, 500);
  };

  return (
    <div className="flex items-center gap-2">
      <button
        onClick={() => handleExport("markdown")}
        disabled={exporting !== null}
        className={cn(
          "flex items-center gap-2 px-3 py-2 rounded-lg text-xs font-medium border transition-all duration-200",
          exported === "markdown"
            ? "bg-success/10 border-success/30 text-success"
            : "bg-card border-border text-foreground hover:bg-accent/50 hover:border-primary/30"
        )}
      >
        {exporting === "markdown" ? (
          <Loader2 className="w-3.5 h-3.5 animate-spin" />
        ) : exported === "markdown" ? (
          <CheckCircle className="w-3.5 h-3.5" />
        ) : (
          <FileText className="w-3.5 h-3.5" />
        )}
        {exported === "markdown" ? "Exported!" : "Export Report"}
      </button>

      <button
        onClick={() => handleExport("json")}
        disabled={exporting !== null}
        className={cn(
          "flex items-center gap-2 px-3 py-2 rounded-lg text-xs font-medium border transition-all duration-200",
          exported === "json"
            ? "bg-success/10 border-success/30 text-success"
            : "bg-card border-border text-foreground hover:bg-accent/50 hover:border-primary/30"
        )}
      >
        {exporting === "json" ? (
          <Loader2 className="w-3.5 h-3.5 animate-spin" />
        ) : exported === "json" ? (
          <CheckCircle className="w-3.5 h-3.5" />
        ) : (
          <FileCode className="w-3.5 h-3.5" />
        )}
        {exported === "json" ? "Exported!" : "Export JSON"}
      </button>
    </div>
  );
}
